_prefs: 
  baselayer: ''
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox</a> <a href='https://openstreetmap.org/about/' target='_blank'>&copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85
  - 180
  - 85
center: 
  - 0
  - 0
  - 3
description: ''
format: "png8:m=h:c=64"
interactivity_layer: ''
layers: null
maxzoom: 19
minzoom: 0
name: Streets
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6"
styles: 
  - vars.mss
  - bg.mss
  - road.mss
  - label.mss
  - poi_classic.mss
  - terrain.mss
template: ''
